# Generated by Django 5.2.5 on 2025-12-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('average', models.FloatField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
